@startmindmap

Title "OCI/VCN - Virtual Cloud Network"
footer Disponível em: https://github.com/acnaweb/oci

*[#F8F8FF]  VCN

**[#LightGray] Load Balancer
***_ Traffic distribution
***_ Automatically rerouting traffic 
***_ Built-in health checks
***_ http/s, tcp, udp
***_ Session statefull: enables stickiness
***_ Policies: least connections - equilibrates
***_ Policies: round-robin (balanced)
***_ Policies: IP hashing
***_ Backend set configuration
***_ Security: WAF -> DDoS protection

@endmindmap
