@startmindmap

Title "Virtual Cloud Network - VCN"

*[#F8F8FF]  VCN

**[#LightGray] Features

***_ Private: Isolated by Tenancy
***_ Customizable IP IPv4 CIDR
***_ class: A -> 10.0.0.0/16 -> 256 subnets
***_ Security list: Virtual firewall for an instance
***_ Route Tables: How traffic between VCN / internet
***_ Internet Gateway: Offers between VCN / internet
***_ NAT Gateway: Instance connections without expose their IP\nPrivate -> Public
***_ Service Gateway: Acesses do Oracle services same region
***_ Dynamic Routing Gateway (DRG): VCN:VNC / VCN:on-premisses, VCN:other clouds
***_ Local Peering Gatewary (LPG): VCN:VNC same region
***_ Remote Peering Gatewary (RPG): LPGs across regions
***_ Network Security Groups(NSG): Virtual firewall for resources within the same VCN

left side

**[#LightGray] Routing Table
***_ Internet Gateway
***_ Out of the VCN
***_ Each rule specifies a destination CIDR block and target inside CIDER
***_ CIDR: 0.0.0.0/0 Internet -> target: Internet Gateway
***_ VCN has default route table that has no rules
***_ Subnet uses a single route table 
***_ Blackholed - traffic droped
***_ Increases infraestructure flexibility

**[#LightGray] Subnets (Tenancy)
***_ Subnet A: 10.0.1.0/24 -> 256 hosts
***_ Subnet B: 10.0.2.0/24 -> 256 hosts
***_ Regional or specific to an AD
***_ VNIC (IP): attach to instance - same route table/Securit Lists/NSG
***_ Public (internet) or Private (db, patch)

@endmindmap
