@startmindmap OCI - Database Services

title "OCI - Database Services"
footer Disponível em: https://github.com/acnaweb/oci

*[#F8F8FF]  Database Services

**[#LightGray] Oracle Public Cloud
***_ VM - Base Database Service (RAC)
***_ Exatada Database Service Dedicated (Data Center)
***_ Autonomous Database Shared/Dedicated Exatada \nManaged Service

**[#LightGray] Cloud@Customer(Customer Data Center)
***_ ExaCC - Exatada Database Service on Cloud@Customer (CDB)
***_ Autonomous Database on Exatada Cloud@Customer (PDB)

@endmindmap
